partition: quake,normal
inputDir: Example_data 
outputDir: Example_merged_output
plates:
    - SequencingRun_001/Plate_001
    - SequencingRun_001/Plate_002
    - SequencingRun_002/Plate_003
    - SequencingRun_002/Plate_004
refFasta: Example_genome/genome.ercc.fasta
annotation: Example_genome/genome.ercc.gff3
htseq_mode: unique
star_keep: one
picard: "java -jar /home/soso/Tools/picard.jar"
outname: Example_data
