partition: quake,normal
inputDir: Example_data 
outputDir: Example_merged_output
plates:
    - SequencingRun_001/Plate_001
    - SequencingRun_001/Plate_002
    - SequencingRun_002/Plate_003
    - SequencingRun_002/Plate_004
refFasta: Example_genome/genome.ercc.fasta
annotation: Example_genome/genome.ercc.gff3
htseq_mode: unique
star_keep: one
outname: Example_data
picard: "java -jar /home/users/yuanxue/picard.jar"
annotated_cdna:
    - /oak/stanford/groups/quake/yuanxue/resources/sc_pipeline/reference_genomes/ToxoplasmaG_ME49_genome/ToxoDB-36_TgondiiME49_AnnotatedTranscripts.fasta.gz
    - /oak/stanford/groups/quake/yuanxue/resources/sc_pipeline/reference_genomes/Mus_musculus_genome/Mus_musculus.GRCm38.cdna.all.fa.gz 
